# Generated by Django 3.1.1 on 2020-10-27 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATodoGasApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idcategoria', models.AutoField(db_column='IDcategoria', primary_key=True, serialize=False)),
                ('nombrecategoria', models.CharField(db_column='nombreCategoria', max_length=30, unique=True)),
                ('descripcategoria', models.CharField(blank=True, db_column='descripCategoria', max_length=100, null=True)),
            ],
            options={
                'db_table': 'categoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Detalleingreso',
            fields=[
                ('idingreso_deta', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio_unidad', models.FloatField()),
                ('total', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'detalleingreso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Detalleventa',
            fields=[
                ('idventadet', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('preciouni', models.FloatField()),
                ('total', models.FloatField()),
            ],
            options={
                'db_table': 'detalleventa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('iddevolucion', models.AutoField(primary_key=True, serialize=False)),
                ('observacion', models.CharField(blank=True, max_length=250, null=True)),
                ('fecha_devoluvcion', models.DateField()),
            ],
            options={
                'db_table': 'devolucion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('idingreso', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('total_ingreso', models.FloatField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'ingreso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('idinventario', models.AutoField(primary_key=True, serialize=False)),
                ('stock', models.IntegerField()),
                ('stockminimo', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'inventario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('idpersona', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(blank=True, max_length=30, null=True)),
                ('telefono', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion', models.CharField(blank=True, max_length=50, null=True)),
                ('municipio', models.CharField(blank=True, max_length=30, null=True)),
                ('identificacion', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'persona',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idproducto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_produc', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('precioventa', models.IntegerField(blank=True, null=True)),
                ('idcategoria', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('idproveedor', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'proveedor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.AutoField(db_column='IDusuario', primary_key=True, serialize=False)),
                ('nombreusuario', models.CharField(db_column='nombreUsuario', max_length=50)),
                ('contrasena', models.CharField(max_length=15)),
                ('cargo', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('idventa', models.AutoField(primary_key=True, serialize=False)),
                ('idcliente', models.IntegerField()),
                ('idusuario', models.IntegerField()),
                ('totalventa', models.FloatField(blank=True, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=30, null=True)),
                ('idfactura', models.IntegerField(blank=True, null=True)),
                ('iva', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'venta',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'managed': False},
        ),
    ]
