# Generated by Django 3.1.1 on 2020-10-27 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ATodoGasApp', '0002_auto_20201026_2202'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cliente',
            table='cliente',
        ),
    ]
